name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_languages_limit: 5
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, makefile, Shell, CMake, Jupyter Notebook
