name: Last.fm personal chart update

on:
  schedule:
    - cron: '2 0 * * *'
  workflow_dispatch:

jobs:
  lastfm:
    runs-on: ubuntu-latest
    steps:
      - name: Lastfm
        uses: lowlighter/metrics@latest
        with:
          filename: music.svg
          token: NOT_NEEDED
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_API_KEY }}
          plugin_music_user: Cururu_dog
          plugin_music_mode: top
          plugin_music_limit: 6
          plugin_music_time_range: long
          plugin_music_top_type: artists
